apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: contact-info
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: contact-info
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: speedypleath/api:latest
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      serviceAccountName: default
      